# Generated by Django 2.0.1 on 2018-01-24 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vota', '0002_auto_20180124_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enviada', models.BooleanField(default=False)),
                ('acceptada', models.BooleanField(default=False)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota.Consulta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opcio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('comentari', models.TextField(default=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota.Consulta')),
            ],
        ),
        migrations.CreateModel(
            name='Vot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota.Opcio')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vota.Consulta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
