# Generated by Django 2.0.1 on 2018-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0004_opcio_usuari'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcio',
            name='vots',
            field=models.IntegerField(default=0),
        ),
    ]
