# Generated by Django 2.0.1 on 2018-02-08 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0008_auto_20180201_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vot',
            name='usuari',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
