# Generated by Django 2.0.1 on 2018-02-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0009_auto_20180208_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vot',
            name='usuari',
            field=models.TextField(null=True),
        ),
    ]
