# Generated by Django 2.0.1 on 2018-02-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vota', '0010_auto_20180208_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vot',
            name='usuari',
        ),
    ]
